ci: add close() to _TeeOut to remove ignored exception when python exits
It would print out the following in *some* versions of Python.

  Exception ignored in: <_io.TextIOWrapper encoding='UTF-8'>
  AttributeError: '_TeeOut' object has no attribute 'close'

This is because we replace sys.stdout with our _TeeOut object and
so then sys.stdout.close() called by python as it shuts down will
fail.

Signed-off-by: julia <git.ts@trainwit.ch>